import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Innovatio | Blogchain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-customColor-innovatio" lang="en">
      <body className={`flex bg-customColor-innovatio flex-col min-h-screen ${inter.className}`}>
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
